[build]
  command = "pnpm install && pnpm run build"
  functions = "netlify/functions"
  publish = "dist/spa"

[dev]
  command = "pnpm run dev"
  framework = "react"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"
  timeout = 30

[[functions]]
  name = "reconcile"
  memory = 3008
  timeout = 30

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/:splat"
